"""
This module has mappings for different workflows
"""
ChangeJobMap = {
    "Fields": "",
    "Spreadsheet Key*": "",
    "Worker*": "employee id",
    "Position": "position id",
    "Effective Date*": "effective date",
    "Reason*": "reason",
    "Supervisory Organization": "supervisory organization",
    "Headcount Option": "headcount option",
    "Job Overlap Allowed": "job overlap allowed",
    "Proposed Position": "proposed position",
    "Proposed Job Requisition": "proposed job requisition",
    "Create Position": "create position",
    "Employee Type": "employee type",
    "Contingent Worker Type": "contingent worker type",
    "Job Profile": "job profile",
    "Position Title": "position title",
    "Business Title": "business title",
    "Location": "location",
    "Work Space": "work space",
    "Position Time Type": "position time type",
    "Time Type Subtype for Worker Event": "time type subtype for worker event",
    "Work Shift": "work shift",
    "Work Hours Profile": "work hours profile",
    "Default Hours": "default hours",
    "Scheduled Hours": "scheduled hours",
    "Working Time Frequency": "working time frequency",
    "Working Time Unit": "working time unit",
    "Working Time Value": "working time value",
    "Specify Paid FTE": "specify paid fte",
    "Paid FTE": "paid fte",
    "Specify Working FTE": "specify working fte",
    "Working FTE": "working fte",
    "Pay Rate Type": "pay rate type",
    "Additional Job Classifications+": "",
    "Company Insider Type+": "",
    "Annual Work Period": "",
    "Disbursement Plan Period": "",
    "Work Study": "",
    "Workers  Compensation Code Override": "",
    "Appointment Type for Worker Event": "",
    "Employee Tenure for Worker Event": "",
    "Annuitant Indicator for Worker Event": "",
    "System ID": "",
    "External ID*": "",
    "Assignment Type": "assignment type",
    "Expected Assignment End Date": "expected assignment end date",
    "End Employment Date": "end employment date",
    "Contract End Date": "contract end date",
    "First Day of Work": "first day of work",
    "Notify Worker By": "notify worker by",
    "New Position ID": "new position id",
    "Contract Pay Rate": "contract pay rate",
    "Currency": "currency",
    "Frequency": "frequency",
    "Contract Assignment Details": "contract assignment details"
}

WDChangeJobMap = {value: key for key, value in ChangeJobMap.items()}
